//! **sdirstat** — a fast, parallel disk-usage analyzer.
//!
//! One parallel scan builds a directory tree whose every node carries its own size; a single
//! reverse-pass fold gives each subtree's total (`own + Σ children`). From that you can read the
//! grand total or emit a nested JSON tree or a QDirStat cache file. The scanner is byte-exact with
//! `du` and has **zero dependencies** (std only).
//!
//! ```no_run
//! let tree = sdirstat::scan("/usr", &sdirstat::Config::default());
//! println!("{} bytes across {} entries", tree.total(), tree.entries());
//! std::fs::write("usr.json", tree.to_json()).unwrap();
//! ```

// Internal modules — implementation detail, not a stable API (hidden from the docs).
#[doc(hidden)]
pub mod hash;
#[cfg(all(target_os = "linux", target_arch = "x86_64"))]
#[doc(hidden)]
pub mod uring;
#[doc(hidden)]
pub mod internal;

use std::path::Path;

/// How to scan. Start from [`Config::default`] and tweak.
#[derive(Clone, Copy, Debug)]
pub struct Config {
    /// Maximum recursion depth (default 40).
    pub max_depth: u32,
    /// Children kept per directory in pruned [`Tree::to_json`] output (default 80).
    pub top: usize,
    /// Worker threads; `0` = auto (one per CPU).
    pub threads: usize,
    /// Count apparent size (`st_size`) instead of allocated blocks.
    pub apparent: bool,
    /// Stay on the root filesystem (`du -x`); don't cross mount points.
    pub one_file_system: bool,
    /// OOM-guard entry ceiling (default 32M; `usize::MAX` = unlimited).
    pub max_entries: usize,
    /// Use the io_uring batched-`statx` backend (Linux x86-64; a no-op elsewhere).
    pub iouring: bool,
}

impl Default for Config {
    fn default() -> Self {
        Config {
            max_depth: 40,
            top: 80,
            threads: 0,
            apparent: false,
            one_file_system: false,
            max_entries: internal::DEFAULT_MAX_ENTRIES,
            iouring: false,
        }
    }
}

impl Config {
    fn to_cfg(&self) -> internal::Cfg {
        internal::Cfg {
            max_depth: self.max_depth,
            top: self.top,
            threads: self.threads,
            apparent: self.apparent,
            no_stat: false,
            iouring: self.iouring,
            max_entries: self.max_entries,
            one_fs: self.one_file_system,
        }
    }
}

/// A scanned, size-folded directory tree. Produced by [`scan`].
pub struct Tree {
    nodes: Vec<internal::Node>,
    kids: hash::Csr,
    top: usize,
}

impl Tree {
    /// Grand total size of the scanned root, in bytes.
    pub fn total(&self) -> u64 {
        self.nodes.first().map(|n| n.sub).unwrap_or(0)
    }

    /// Number of entries scanned (nodes in the tree).
    pub fn entries(&self) -> usize {
        self.nodes.len()
    }

    /// The scanned root's name (its canonical path).
    pub fn root(&self) -> &str {
        self.nodes.first().map(|n| n.name.as_str()).unwrap_or("")
    }

    /// The nested tree as JSON: `{"n":name,"v":bytes,"d":1|0,"c":[…]}`. Each directory keeps its
    /// [`Config::top`] largest children, the remainder bucketed into one `"… (k more)"` leaf, so
    /// totals stay exact while the tree stays bounded.
    pub fn to_json(&self) -> String {
        let cfg = self.cfg_for_emit();
        let mut acc = hash::Acc::with_capacity(self.nodes.len().saturating_mul(48).max(1 << 16));
        internal::emit_json(0, &self.kids, &self.nodes, &cfg, &mut acc);
        acc.into_string()
    }

    /// The tree in the QDirStat 2.0 cache format — a drop-in for `qdirstat-cache-writer`.
    pub fn to_qdirstat_cache(&self) -> String {
        let mut acc = hash::Acc::with_capacity(self.nodes.len().saturating_mul(96).max(1 << 16));
        acc.str("[qdirstat 2.0 cache file]\n# Generated by sdirstat\n# Do not edit!\n#\n");
        let root_name = self.nodes[0].name.clone();
        internal::cache_dir(&mut acc, 0, &root_name, &self.kids, &self.nodes);
        acc.into_string()
    }

    // `emit_json` reads only `cfg.top`; the rest is filler.
    fn cfg_for_emit(&self) -> internal::Cfg {
        internal::Cfg {
            max_depth: 0, top: self.top, threads: 0, apparent: false,
            no_stat: false, iouring: false, max_entries: 0, one_fs: false,
        }
    }
}

/// Scan a directory tree and fold subtree sizes.
///
/// The walk is parallel and schedule-free; the fold is one reverse pass over the arena
/// (parent precedes child), so this is `O(entries)` time and memory. Byte-exact with `du`
/// (allocated `st_blocks × 512` by default; set [`Config::apparent`] for logical size).
pub fn scan(root: impl AsRef<Path>, cfg: &Config) -> Tree {
    let c = cfg.to_cfg();
    let root = root.as_ref();
    let canon = std::fs::canonicalize(root).unwrap_or_else(|_| root.to_path_buf());
    let mut nodes = internal::scan_backend(root, canon.to_string_lossy().into_owned(), &c);
    // the size fold — one reverse pass; identical to the in-binary fold (no perf change).
    for i in (1..nodes.len()).rev() {
        let s = nodes[i].sub;
        let p = nodes[i].parent;
        nodes[p].sub += s;
    }
    let kids = hash::Csr::from_parents(nodes.len(), |i| nodes[i].parent);
    Tree { nodes, kids, top: cfg.top }
}
